export const ACTION_TYPES = {
  // Auth Actions
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  
  // Course Actions
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_FAILURE: 'FETCH_COURSES_FAILURE',
  FETCH_COURSE_SUCCESS: 'FETCH_COURSE_SUCCESS',
  FETCH_COURSE_FAILURE: 'FETCH_COURSE_FAILURE',
  
  // Progress Actions
  UPDATE_PROGRESS: 'UPDATE_PROGRESS',
  FETCH_PROGRESS_SUCCESS: 'FETCH_PROGRESS_SUCCESS',
  FETCH_PROGRESS_FAILURE: 'FETCH_PROGRESS_FAILURE',
  
  // User Actions
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  
  // Loading Actions
  SET_LOADING: 'SET_LOADING',
  CLEAR_ERROR: 'CLEAR_ERROR'
}
